query Brands($slug: String) {
  couponEntityCollection(where: {slug: $slug}) {
    items {
      sys {
        id
      }
      name
      slug
      logoImage {
        url
      }
      description
      category {
        description
        image {
          url
        }
        name
      }
      linkedFrom {
        couponEntryCollection {
          total
        }
      }
      brandUrl
    }
  }
}
