query Coupons($active: Boolean, $brandId: String, $slug: String) {
  couponEntryCollection(where: {active: $active, slug: $slug, brandEntity: {sys: {id: $brandId}}}) {
    items {
      title
      slug
      bannerImagesCollection {
        items {
          url
        }
      }
      brandEntity {
        sys {
          id
        }
        logoImage {
          url
        }
        slug
      }
      description
      expiresAt
      referringUrl
      sys {
        id
      }
    }
  }
}
